python: 
- 3.5
- 3.6
- 3.7

matrix:
  include:
    - language: python

      cache: pip

      install: 
      - cd python
      - python setup.py -q install

      script:
      - python setup.py -q test
    - language: go
